import { callModelJSON } from "../clients/llmClient.js";
import { SAFETY_CONSTRAINTS, DISCLAIMER } from "../lib/safetyConstraints.js";

// Same bar Module 2 uses for "clearly relevant" — reused here as a signal
// for whether the body of evidence feeding this synthesis is actually solid.
const WEAK_EVIDENCE_THRESHOLD = 6;
// If at least this fraction of scored summaries fall below the threshold,
// treat the overall evidence as weak.
const WEAK_EVIDENCE_RATIO = 0.5;

function assessEvidenceQuality(caseSummaries) {
  const scored = caseSummaries.filter((c) => typeof c.relevanceScore === "number");
  const weakCount = scored.filter((c) => c.relevanceScore < WEAK_EVIDENCE_THRESHOLD).length;
  const isWeak = scored.length === 0 || weakCount / scored.length >= WEAK_EVIDENCE_RATIO;

  return { totalCases: caseSummaries.length, scoredCases: scored.length, weakCases: weakCount, isWeak };
}

const SYSTEM_PROMPT = `
You are a legal research assistant producing a cross-case synthesis for a
user researching their legal situation, based on several already-summarized
Indian court judgments retrieved as potentially similar cases.

You will be given the user's original case context (category, key facts,
parties), an array of individual case summaries (facts, legalIssue,
arguments, decision, relevanceAnalysis, relevanceScore for each retrieved
judgment), and a note on how many of those summaries scored below a
relevance threshold — i.e. how much of the underlying evidence is weak or
borderline rather than strongly on-point.

Produce:
- commonPatterns: what these cases collectively suggest — recurring legal
  reasoning, doctrines, or outcomes shared across the summaries given to
  you. Only draw on claims already present in those summaries.
- divergence: any notable disagreement or distinction between the cases —
  e.g. different courts reaching different conclusions on similar facts, or
  cases that are only superficially similar but decided on different
  grounds. If the cases are broadly consistent with no real divergence, say
  so plainly rather than inventing a false disagreement.
- relevanceToUserCase: an overall synthesis of how this body of case law —
  collectively, not case-by-case — applies to the user's specific
  situation, referencing their actual facts.
- weakEvidenceNote: if a significant portion of the input summaries have a
  low relevance score, explicitly say the available precedent is limited or
  weak, rather than presenting a confident-sounding synthesis from thin
  evidence. If the evidence is actually strong, say so briefly instead (e.g.
  "The retrieved cases were consistently on-point.").

Do NOT include any Indian Kanoon URLs, doc links, or citation links
anywhere in your response, including for cases mentioned only in passing —
the system attaches verified source URLs separately from trusted metadata,
never from anything you generate.

Respond with ONLY a JSON object of this shape:
{
  "commonPatterns": string,
  "divergence": string,
  "relevanceToUserCase": string,
  "weakEvidenceNote": string
}

${SAFETY_CONSTRAINTS}
`.trim();

const REQUIRED_FIELDS = ["commonPatterns", "divergence", "relevanceToUserCase", "weakEvidenceNote"];

function validateShape(result) {
  for (const field of REQUIRED_FIELDS) {
    if (!(field in result) || typeof result[field] !== "string") {
      throw new Error(
        `Synthesis output is missing or has an invalid "${field}" field. Got: ${JSON.stringify(result)}`
      );
    }
  }
}

/**
 * Module 5: Cross-Case Synthesis
 * Input: array of per-case summaries from Module 4, plus the user's context
 *        from Module 1
 * Output: { commonPatterns, divergence, relevanceToUserCase, weakEvidenceNote,
 *           sources, disclaimer }
 * `sources` is assembled directly from each summary's `sourceUrl` — trusted
 * structured data, never asked of or regenerated by the LLM.
 */
export async function synthesizeCases(caseSummaries, userContext) {
  const sources = caseSummaries.map((c) => c.sourceUrl).filter(Boolean);

  if (caseSummaries.length === 0) {
    return {
      commonPatterns: "No case summaries were available to synthesize.",
      divergence: "",
      relevanceToUserCase:
        "No relevant case law could be retrieved for this situation based on the searches performed.",
      weakEvidenceNote:
        "No candidate cases cleared even the minimum relevance bar for this search — this may indicate " +
        "that reported precedent is scarce for this specific fact pattern, not that no legal remedy exists.",
      sources,
      disclaimer: DISCLAIMER,
    };
  }

  const evidenceQuality = assessEvidenceQuality(caseSummaries);

  const prompt = JSON.stringify({
    userContext: {
      rawDescription: userContext.rawDescription ?? null,
      category: userContext.category,
      keyFacts: userContext.keyFacts,
      parties: userContext.parties,
    },
    caseSummaries: caseSummaries.map((c) => ({
      title: c.title,
      court: c.court,
      date: c.date,
      relevanceScore: c.relevanceScore,
      facts: c.facts,
      legalIssue: c.legalIssue,
      arguments: c.arguments,
      decision: c.decision,
      relevanceAnalysis: c.relevanceAnalysis,
    })),
    evidenceQualitySignal: evidenceQuality,
  });

  const result = await callModelJSON(prompt, SYSTEM_PROMPT, "reasoning");
  validateShape(result);

  return {
    commonPatterns: result.commonPatterns,
    divergence: result.divergence,
    relevanceToUserCase: result.relevanceToUserCase,
    weakEvidenceNote: result.weakEvidenceNote,
    sources,
    disclaimer: DISCLAIMER,
  };
}
